const ActionTypes = {
  SET_THEME: "SET_THEME",
  SET_LANGUAGE: "SET_LANGUAGE",
  SET_LOADING: "SET_LOADING",
  SET_TRAINLIST: "SET_TRAINLIST",
  SET_SEATLIST: "SET_SEATLIST",
  SET_TICKETLIST: "SET_TICKETLIST",
};

export default ActionTypes;
